lib/my_site_web/router.ex
defmodule MySiteWeb.Router do
  use MySiteWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MySiteWeb.Visitor do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/posts", PostController, :index
    get "/posts/:slug", PostController, :show
    get "/comments/:slug", CommentController, :show
  end

  scope "/admin", MySiteWeb.Admin, as: :admin do
    pipe_through :browser

    resources "/posts", PostController do
      resources "/comments", CommentController
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", MySiteWeb do
  #   pipe_through :api
  # end
end

lib/my_site/blog/post.ex
defmodule MySite.Blog.Post do
  use Ecto.Schema

  import Ecto.Changeset

  alias MySite.Blog.Post
  alias MySite.Blog.Comment

  schema "posts" do
    field :body, :string
    field :read_time, :integer
    field :title, :string
    has_many :comments, Comment, on_delete: :delete_all

    timestamps()
  end

  @doc false
  def changeset(%Post{} = post, attrs) do
    post
    |> cast(attrs, [:title, :body, :read_time])
    |> validate_required([:title, :body, :read_time])
  end
end

lib/my_site_web/controllers/admin/post_controller.ex
defmodule MySiteWeb.Admin.PostController do
  use MySiteWeb, :controller

  alias MySite.Blog
  alias MySite.Blog.Post

  def index(conn, _params) do
    posts = Blog.list_posts()
    render(conn, "index.html", posts: posts)
  end

  def new(conn, _params) do
    changeset = Blog.change_post(%Post{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"post" => post_params}) do
    case Blog.create_post(post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post created successfully.")
        |> redirect(to: admin_post_path(conn, :show, post))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    post = Blog.get_post!(id)
    comments = Blog.list_comments(id)
    render(conn, "show.html", post: post, comments: comments)
  end

  def edit(conn, %{"id" => id}) do
    post = Blog.get_post!(id)
    changeset = Blog.change_post(post)
    render(conn, "edit.html", post: post, changeset: changeset)
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = Blog.get_post!(id)

    case Blog.update_post(post, post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post updated successfully.")
        |> redirect(to: admin_post_path(conn, :show, post))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", post: post, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    post = Blog.get_post!(id)
    {:ok, _post} = Blog.delete_post(post)

    conn
    |> put_flash(:info, "Post deleted successfully.")
    |> redirect(to: admin_post_path(conn, :index))
  end
end

lib/my_site_web/controllers/visitor/comment_controller.ex
defmodule MySiteWeb.Visitor.CommentController do
  use MySiteWeb, :controller

  import MySiteWeb.Visitor.SlugHelper
  
  alias MySite.Blog

  plug :extract_id_from_slug

  def show(conn, _params) do
    comment = Blog.get_comment!(conn.assigns[:id])
    post = Blog.get_post!(comment.post_id)
    render(conn, "show.html", comment: comment, post: post)
  end
end

lib/my_site_web/controllers/visitor/page_controller.ex
defmodule MySiteWeb.Visitor.PageController do
  use MySiteWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/my_site_web/controllers/visitor/post_controller.ex
defmodule MySiteWeb.Visitor.PostController do
  use MySiteWeb, :controller

  import MySiteWeb.Visitor.SlugHelper

  alias MySite.Blog

  plug :extract_id_from_slug when action in [:show]

  def index(conn, _params) do
    posts = Blog.list_posts()
    render(conn, "index.html", posts: posts)
  end

  def show(conn, _params) do
    post = Blog.get_post!(conn.assigns[:id])
    comments = Blog.list_comments(conn.assigns[:id])
    render(conn, "show.html", post: post, comments: comments)
  end
end

lib/my_site_web/views/admin/post_view.ex
defmodule MySiteWeb.Admin.PostView do
  use MySiteWeb, :view
end

lib/my_site_web/views/visitor/comment_view.ex
defmodule MySiteWeb.Visitor.CommentView do
  use MySiteWeb, :view
end

lib/my_site_web/views/visitor/page_view.ex
defmodule MySiteWeb.Visitor.PageView do
  use MySiteWeb, :view
end

lib/my_site_web/views/visitor/post_view.ex
defmodule MySiteWeb.Visitor.PostView do
  use MySiteWeb, :view
end

lib/my_site_web/templates/visitor/post/index.html.eex
<h2>Listing Posts</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Read time</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for post <- @posts do %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.body %></td>
      <td><%= post.read_time %></td>

      <td class="text-right">
        <span><%= link "Show", to: post_path(@conn, :show, %MySite.Blog.Slug{resource: post}), class: "btn btn-default btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

lib/my_site_web/templates/visitor/post/show.html.eex
<h2>Show Post</h2>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @post.title %>
  </li>

  <li>
    <strong>Body:</strong>
    <%= @post.body %>
  </li>

  <li>
    <strong>Read time:</strong>
    <%= @post.read_time %>
  </li>

</ul>

<h4>Comments</h4>

<%= for comment <- @comments do %>
<p><b><%= comment.title %></b> by <%= comment.author_name %></p>
<p><%= comment.body %></p>
<p><%= link "Show", to: comment_path(@conn, :show, %MySite.Blog.Slug{resource: comment}), class: "btn btn-default btn-xs" %></p>

<hr>
<% end %>

<span><%= link "Back", to: post_path(@conn, :index) %></span>